version: '3.8'

services:
  web:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py runserver 0.0.0.0:8002"
    # любые изменения в файлах на хосте появляются и в докере, и наоборот, если контейнер создает файлы в tsp, то они сохраняются на компе
    volumes:
      - .:/tsp
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8001:8002
    depends_on:
      - db

  db:
    image: postgres
    # 5432 - порт для постгрес, 5436 - порт на нашем компе
    ports:
      - 5436:5431
    environment:
      POSTGRES_DB: tsp_database
      POSTGRES_USER: alsu
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes: # нужен для того, чтобы хранить данные вне контейнера
  pgdata: null # если не напишем это и удалим контейнер, то данные удалятся вместе с ним
