# Generated by Django 5.1.7 on 2025-04-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp_database_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofplaces',
            name='placemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_places', to='tsp_database_app.placemodel'),
        ),
        migrations.AlterField(
            model_name='listofplaces',
            name='usermodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placemodel',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
